import {Queue,Worker} from 'bullmq';
import {createConnection} from 'node:net';
import {GetObjectCommand,PutObjectCommand} from '@aws-sdk/client-s3';
import {db} from './database';
import {s3,bucket,readUrl} from './storage';
import {canonical,sha256,permitted} from './domain';
const redis=new URL(process.env.REDIS_URL||'redis://localhost:6379');
const connection={host:redis.hostname,port:Number(redis.port||6379),...(redis.password?{password:decodeURIComponent(redis.password)}:{}),...(redis.protocol==='rediss:'?{tls:{}}:{})};
const names=['evidence-process','transcribe','frame-index','entity-event-extract','timeline-refresh','graph-refresh','conflict-refresh','reconstruction','integrity-check','stellar-anchor','stellar-confirm','export-build'] as const;
const queues=new Map<string,Queue>(names.map(n=>[n,new Queue(n,{connection,defaultJobOptions:{attempts:5,backoff:{type:'exponential',delay:3000},removeOnComplete:false,removeOnFail:false}})]));
async function scan(key:string,version:string){if(!process.env.CLAMAV_HOST)throw new Error('Malware scanner not configured; evidence remains quarantined');const object=await s3.send(new GetObjectCommand({Bucket:bucket,Key:key,VersionId:version}));await new Promise<void>((resolve,reject)=>{const socket=createConnection({host:process.env.CLAMAV_HOST!,port:Number(process.env.CLAMAV_PORT||3310)});let response='';socket.setTimeout(120000,()=>socket.destroy(new Error('Malware scan timeout')));socket.on('error',reject);socket.on('data',chunk=>response+=chunk.toString());socket.on('end',()=>response.includes('stream: OK')?resolve():reject(new Error('Malware scan failed')));socket.on('connect',async()=>{try{socket.write('zINSTREAM\0');for await(const chunk of object.Body as any){const header=Buffer.alloc(4);header.writeUInt32BE(chunk.length);socket.write(header);if(!socket.write(chunk))await new Promise<void>(r=>socket.once('drain',r))}socket.write(Buffer.alloc(4))}catch(error){socket.destroy();reject(error)}})})}
async function callAi(operation:string,payload:object){const r=await fetch(`${process.env.AI_URL}/internal/v1/${operation}`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${process.env.AI_SERVICE_TOKEN}`},body:JSON.stringify(payload),signal:AbortSignal.timeout(240000)});if(!r.ok)throw new Error(`AI processing failed (${r.status})`);return r.json() as Promise<any>}
async function storeObject(key:string,content:string){const digest=sha256(content);const r=await s3.send(new PutObjectCommand({Bucket:bucket,Key:key,Body:content,ContentType:'application/json',IfNoneMatch:'*'}));if(!r.VersionId)throw new Error('Versioned storage required');return {sha256:digest,objectVersionId:r.VersionId}}
async function processEvidence(data:any){const v=await db.evidenceVersion.findUniqueOrThrow({where:{id:data.versionId},include:{evidence:true}});if(v.evidence.caseId!==data.caseId)throw new Error('Case/version mismatch');await scan(v.objectKey,v.objectVersionId);await db.evidenceItem.update({where:{id:v.evidenceId},data:{status:'PROCESSING'}});const recordId=`analysis-${v.id}`;let analysis=(await db.record.findUnique({where:{id:recordId}}))?.data as any;
if(!analysis){analysis=await callAi('process-evidence',{caseId:data.caseId,evidenceId:v.evidenceId,versionId:v.id,sha256:v.sha256,mimeType:v.mimeType,url:await readUrl(v.objectKey,v.objectVersionId)});if(analysis.versionId!==v.id||analysis.evidenceId!==v.evidenceId||analysis.sha256!==v.sha256)throw new Error('AI provenance mismatch');const content=canonical(analysis),key=`derived/${data.caseId}/${v.id}/${sha256(content)}.json`;try{await storeObject(key,content)}catch(error){if((error as any).$metadata?.httpStatusCode!==412)throw error}await db.$transaction(async tx=>{await tx.derivedArtifact.upsert({where:{objectKey:key},create:{versionId:v.id,objectKey:key,sha256:sha256(content),type:'AI_JSON',toolName:'afterprint-ai',toolVersion:'0.1.0',parametersHash:sha256('conservative-source-extraction/0.1')},update:{}});await tx.record.upsert({where:{id:recordId},create:{id:recordId,caseId:data.caseId,kind:`analysis:${v.id}`,data:analysis},update:{}})})}
const all=await db.record.findMany({where:{caseId:data.caseId,kind:{startsWith:'analysis:'}}});const payload={caseId:data.caseId,sources:all.map(r=>r.data)};const timeline=await callAi('build-timeline',payload),graph=await callAi('build-graph',payload),conflicts=await callAi('detect-conflicts',payload);
await db.$transaction(async tx=>{for(const [kind,result] of [['timeline',timeline],['graph',graph]] as const){const id=`${kind}-${data.caseId}`;await tx.record.upsert({where:{id},create:{id,caseId:data.caseId,kind,data:result},update:{data:result,revision:{increment:1}}})}for(const conflict of conflicts){const id=`conflict-${data.caseId}-${conflict.id}`;await tx.record.upsert({where:{id},create:{id,caseId:data.caseId,kind:'conflicts',data:{...conflict,id}},update:{}})}await tx.evidenceItem.update({where:{id:v.evidenceId},data:{status:'PROCESSED'}});await tx.outbox.upsert({where:{id:`anchor-${v.id}`},create:{id:`anchor-${v.id}`,queue:'stellar-anchor',data:{caseId:data.caseId,versionId:v.id}},update:{}})})}
async function exportBundle(data:any){const existing=await db.record.findUniqueOrThrow({where:{id:data.exportId}});if((existing.data as any).status==='READY')return;const membership=await db.caseMember.findUnique({where:{caseId_userId:{caseId:data.caseId,userId:data.actorId}}});if(!membership?.active||!permitted(membership.role,'EVIDENCE_EXPORT'))throw new Error('Export permission revoked');const versions=await db.evidenceVersion.findMany({where:{evidence:{caseId:data.caseId}},include:{custody:{orderBy:{occurredAt:'asc'}},artifacts:true}});const reports=await db.record.findMany({where:{caseId:data.caseId,kind:'reconstruction'}});const payload={schemaVersion:'1.0',caseRef:sha256(data.caseId),evidence:versions.map(v=>({evidenceVersionId:v.id,sha256:v.sha256,sizeBytes:v.size,mimeType:v.mimeType,objectVersionId:v.objectVersionId,custody:v.custody,derivedArtifacts:v.artifacts.map(a=>({id:a.id,sha256:a.sha256,tool:a.toolName,toolVersion:a.toolVersion}))})),reports:reports.filter(r=>(r.data as any).status==='FINALIZED').map(r=>r.data),verification:'Canonicalize payload recursively with lexicographically sorted object keys, preserve array order, then compute UTF-8 SHA-256. Source files require separate authorized retrieval. No legal admissibility is asserted.'};const content=canonical({payload,payloadSha256:sha256(canonical(payload))}),key=`exports/${data.caseId}/${data.exportId}.json`;let stored;try{stored=await storeObject(key,content)}catch(error){if((error as any).$metadata?.httpStatusCode!==412)throw error;const {inspect}=await import('./storage.js');stored=await inspect(key);if(stored.sha256!==sha256(content))throw new Error('Existing export differs from retry')}await db.record.update({where:{id:data.exportId},data:{data:{status:'READY',actorId:data.actorId,manifestHash:sha256(canonical(payload)),objectKey:key,objectVersionId:stored.objectVersionId}}})}
async function anchor(data:any){if(!process.env.STELLAR_ANCHOR_SERVICE_URL)throw new Error('Stellar signing service not configured; anchor remains pending');
if(data.isAttestation){const att=await db.record.findUniqueOrThrow({where:{id:data.attestationId}});const attData=att.data as any;const manifest={schemaVersion:'1.0',caseRef:sha256(data.caseId),attestationRef:sha256(data.attestationId),subjectRef:sha256(data.versionId),statementHash:attData.statementHash};const r=await fetch(process.env.STELLAR_ANCHOR_SERVICE_URL,{method:'POST',headers:{Authorization:`Bearer ${process.env.STELLAR_SIGNER_TOKEN}`,'Content-Type':'application/json','Idempotency-Key':data.attestationId},body:JSON.stringify({evidenceVersionRef:sha256(data.attestationId),manifestHash:sha256(canonical(manifest))}),signal:AbortSignal.timeout(60000)});if(!r.ok)throw new Error('Anchor service rejected request');const result=await r.json() as any;if(!result.transactionHash||result.status!=='CONFIRMED')throw new Error('Anchor is not confirmed');await db.record.upsert({where:{id:`attestation-anchor-${data.attestationId}`},create:{id:`attestation-anchor-${data.attestationId}`,caseId:data.caseId,kind:'attestation-anchor',data:{manifestHash:sha256(canonical(manifest)),transactionHash:result.transactionHash,status:'CONFIRMED'}},update:{data:{manifestHash:sha256(canonical(manifest)),transactionHash:result.transactionHash,status:'CONFIRMED'}}});await db.record.update({where:{id:data.attestationId},data:{data:{...attData,status:'ANCHORED'}}});return}
const v=await db.evidenceVersion.findUniqueOrThrow({where:{id:data.versionId},include:{evidence:true,custody:{orderBy:{occurredAt:'desc'},take:1}}});const manifest={schemaVersion:'1.0',caseRef:sha256(data.caseId),evidenceRef:sha256(v.evidenceId),version:1,sha256:v.sha256,sizeBytes:v.size,mimeType:v.mimeType,importedAt:v.importedAt.toISOString(),sourceMetadataHash:sha256(v.evidence.source),custodyHeadHash:v.custody[0]?.eventHash||''};const r=await fetch(process.env.STELLAR_ANCHOR_SERVICE_URL,{method:'POST',headers:{Authorization:`Bearer ${process.env.STELLAR_SIGNER_TOKEN}`,'Content-Type':'application/json','Idempotency-Key':v.id},body:JSON.stringify({evidenceVersionRef:sha256(v.id),manifestHash:sha256(canonical(manifest))}),signal:AbortSignal.timeout(60000)});if(!r.ok)throw new Error('Anchor service rejected request');const result=await r.json() as any;if(!result.transactionHash||result.status!=='CONFIRMED')throw new Error('Anchor is not confirmed');await db.record.upsert({where:{id:`anchor-${v.id}`},create:{id:`anchor-${v.id}`,caseId:data.caseId,kind:'anchor',data:{manifestHash:sha256(canonical(manifest)),transactionHash:result.transactionHash,status:'CONFIRMED'}},update:{}})}
async function confirmAnchor(data:any){const recordId=`anchor-${data.versionId}`;const existing=await db.record.findUnique({where:{id:recordId}});if(!existing)throw new Error('No anchor record found; stellar-anchor may not have run yet');const d=existing.data as any;if(d.status==='CONFIRMED')return;if(!d.transactionHash)throw new Error('Anchor record has no transaction hash yet');const horizon=process.env.STELLAR_HORIZON_URL||'https://horizon-testnet.stellar.org';const res=await fetch(`${horizon}/transactions/${d.transactionHash}`,{signal:AbortSignal.timeout(30000)});if(!res.ok)throw new Error(`Horizon returned ${res.status} for tx ${d.transactionHash}`);const tx=await res.json() as any;if(!tx.successful)throw new Error('Transaction is not successful on Stellar');await db.record.update({where:{id:recordId},data:{data:{...d,status:'CONFIRMED',ledger:tx.ledger,confirmedAt:new Date().toISOString()}}})}
async function refreshCase(data:any){const {caseId}=data;if(!caseId)throw new Error('caseId required for refresh');const all=await db.record.findMany({where:{caseId,kind:{startsWith:'analysis:'}}});if(!all.length)return;const payload={caseId,sources:all.map(r=>r.data)};const [timeline,graph,conflicts]=await Promise.all([callAi('build-timeline',payload),callAi('build-graph',payload),callAi('detect-conflicts',payload)]);await db.$transaction(async tx=>{for(const [kind,result] of [['timeline',timeline],['graph',graph]] as const){const id=`${kind}-${caseId}`;await tx.record.upsert({where:{id},create:{id,caseId,kind,data:result},update:{data:result,revision:{increment:1}}})}for(const conflict of conflicts){const id=`conflict-${caseId}-${conflict.id}`;await tx.record.upsert({where:{id},create:{id,caseId,kind:'conflicts',data:{...conflict,id}},update:{}})}})}
const workers=names.map(name=>{const w=new Worker(name,job=>{if(['evidence-process','transcribe','frame-index','entity-event-extract'].includes(name))return processEvidence(job.data);if(name==='export-build')return exportBundle(job.data);if(name==='stellar-anchor')return anchor(job.data);if(name==='stellar-confirm')return confirmAnchor(job.data);if(['timeline-refresh','graph-refresh','conflict-refresh'].includes(name))return refreshCase(job.data);return Promise.resolve()},{connection,concurrency:2});w.on('failed',(job,error)=>{console.error(JSON.stringify({event:'job_failed',jobId:job?.id,queue:name,attempt:job?.attemptsMade,errorType:error.name,deadLetter:job?.attemptsMade===5}))});return w});
let polling=false;const interval=setInterval(async()=>{if(polling)return;polling=true;try{for(const row of await db.outbox.findMany({where:{sentAt:null},take:50})){await queues.get(row.queue)!.add(row.queue,row.data,{jobId:row.id});await db.outbox.update({where:{id:row.id},data:{sentAt:new Date()}})}}catch(error){console.error(JSON.stringify({event:'outbox_retry',errorType:(error as Error).name}))}finally{polling=false}},1000);
async function shutdown(){clearInterval(interval);await Promise.all(workers.map(w=>w.close()));await Promise.all([...queues.values()].map(q=>q.close()));await db.$disconnect();process.exit(0)}process.on('SIGTERM',shutdown);process.on('SIGINT',shutdown);
